#!/bin/bash
#SBATCH --job-name=TASK_NAME
#SBATCH --time=96:00:00
#SBATCH --nodes=10 
#SBATCH --ntasks-per-node=24
#SBATCH --cpus-per-task=2
#SBATCH --mem=384000
#SBATCH --account=ACCOUNT_NAME
#SBATCH --mail-user=EMAIL@gmail.com
#SBATCH --mail-type=END
#SBATCH --error=error.txt
#SBATCH --output=output.txt
 
module load espresso

export OMP_NUM_THREADS=2

PPN=$(( $SLURM_NTASKS_PER_NODE * $SLURM_JOB_NUM_NODES ))
echo "number of MPI processes PPN = $PPN"
echo "number of OpenMP threads OMP_NUM_THREADS = $OMP_NUM_THREADS"

### Yambo
mpirun   -np $PPN  yambo -F yambo1.in 
 




