#!/bin/bash
#SBATCH --time=24:00:00
#SBATCH --nodes=10 
#SBATCH --ntasks-per-node=48
#SBATCH --cpus-per-task=1
#SBATCH --mem=384000
#SBATCH --job-name=TASK_NAME
#SBATCH --mail-type=END
#SBATCH --account=ACCOUNT_NAME
#SBATCH --mail-user=EMAIL@gmail.com
#SBATCH --error=error.txt
#SBATCH --output=output.txt
 
module load espresso

export OMP_NUM_THREADS=1

PPN=$(( $SLURM_NTASKS_PER_NODE * $SLURM_JOB_NUM_NODES / $OMP_NUM_THREADS ))
echo "number of MPI processes PPN = $PPN"
echo "number of OpenMP threads OMP_NUM_THREADS = $OMP_NUM_THREADS"

### Yambo
mpirun   -np $PPN  yambo -F yambo1.in 
 




