#!/bin/bash
#SBATCH --time=1:00:00
#SBATCH --nodes=2 
#SBATCH --ntasks-per-node=48
#SBATCH --mem=384000
#SBATCH --job-name=NAME
#SBATCH --mail-type=END
#SBATCH --account=ACCOUNT
#SBATCH --mail-user=EMAIL@gmail.com
#SBATCH --error=error.txt
#SBATCH --output=output.txt
 
module load espresso

export MV2_ENABLE_AFFINITY=0 
export I_MPI_PIN_DOMAIN=auto 
export I_MPI_PIN_ORDER=bunch 
export KMP_AFFINITY=compact,granularity=fine,1 
export OMP_NUM_THREADS=1

PPN=$(( $SLURM_NTASKS_PER_NODE * $SLURM_JOB_NUM_NODES / $OMP_NUM_THREADS ))
echo "number of MPI processes PPN = $PPN"
echo "number of OpenMP threads OMP_NUM_THREADS = $OMP_NUM_THREADS"

### Quantum Espresso:
mpirun -np $PPN pw.x -ni 1 -nk 2 -nt 2 -nd 1 -nb 2 -input scf.in > scf.out
mpirun -np $PPN pw.x -ni 1 -nk 1 -nt 1 -nd 1 -nb 1 -input nscf.in > nscf.out

### Convert to Yambo: 
cd d.save
p2y
yambo






