#!/bin/bash
#SBATCH --time=1:00:00
#SBATCH --nodes=1 
#SBATCH --ntasks-per-node=32
#SBATCH --job-name=QE
#SBATCH --mail-type=END
#SBATCH --account=<account name>
#SBATCH --mail-user=<email@gmail.com>
#SBATCH --error=error.txt
#SBATCH --output=output.txt
 
module load espresso

export MV2_ENABLE_AFFINITY=0 
export I_MPI_PIN_DOMAIN=auto 
export I_MPI_PIN_ORDER=bunch 
export KMP_AFFINITY=compact,granularity=fine,1 
export OMP_NUM_THREADS=1

PPN=$(( $SLURM_TASKS_PER_NODE / $OMP_NUM_THREADS ))
echo "PPN = $PPN"

### Quantum Espresso scf
mpirun -ppn $PPN pw.x -ni 1 -nk 1 -nt 1 -nd 16 -nb 1 -input scf.in > scf.out

### Quantum Espresso nscf
mpirun -ppn $PPN pw.x -ni 1 -nk 1 -nt 1 -nd 16 -nb 1 -input nscf.in > nscf.out




