#!/bin/bash
#SBATCH --job-name=NAME
#SBATCH --time=1:00:00
#SBATCH --nodes=2 
#SBATCH --ntasks-per-node=48
#SBATCH --cpus-per-task=1
#SBATCH --mem=384000
#SBATCH --account=ACCOUNT_NAME
#SBATCH --mail-user=EMAIL@gmail.com
#SBATCH --mail-type=END
#SBATCH --error=error.txt
#SBATCH --output=output.txt
 
module load espresso

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export MV2_ENABLE_AFFINITY=0 
export I_MPI_PIN_DOMAIN=auto 
export I_MPI_PIN_ORDER=bunch 
export KMP_AFFINITY=compact,granularity=fine,1

PPN=$(( $SLURM_NTASKS_PER_NODE * $SLURM_JOB_NUM_NODES ))
echo "number of MPI processes   = $PPN"
echo "number of OpenMP threads  = $OMP_NUM_THREADS"

### Quantum Espresso:
mpirun -np $PPN pw.x -ni 1 -nk 2  -nt 2 -nd 1 -nb 2 -input scf.in > scf.out
mpirun -np $PPN pw.x -ni 1 -nk 12 -nt 1 -nd 1 -nb 1 -input nscf.in > nscf.out








