#!/bin/bash
#SBATCH --job-name=hBN_SHG
#SBATCH --time=96:00:00
#SBATCH --nodes=10 
#SBATCH --ntasks-per-node=48
#SBATCH --cpus-per-task=1
#SBATCH --mem=384000
#SBATCH --account=ACCOUNT
#SBATCH --mail-user=EMAIL@gmail.com
#SBATCH --mail-type=END
#SBATCH --error=error.txt
#SBATCH --output=output.txt

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export MV2_ENABLE_AFFINITY=0 
export I_MPI_PIN_DOMAIN=auto 
export I_MPI_PIN_ORDER=bunch 
export KMP_AFFINITY=compact,granularity=fine,1
 
module load espresso

PPN=$(( $SLURM_NTASKS_PER_NODE * $SLURM_JOB_NUM_NODES ))
echo "number of MPI processes   = $PPN"
echo "number of OpenMP threads  = $OMP_NUM_THREADS"

### Yambo
mpirun   -np $PPN  yambo_nl -F yambo_shg.in 




